// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatMessage struct {
	ID        uuid.UUID
	RoomID    uuid.UUID
	Message   string
	Player    uuid.UUID
	CreatedAt pgtype.Date
}

type Game struct {
	ID        uuid.UUID
	Rodada    int32
	CreatedAt pgtype.Date
	Result    []byte
	Players   []uuid.UUID
	State     interface{}
}

type Player struct {
	ID   uuid.UUID
	Name string
}
