// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package pgstore

import (
	"context"
)

const getRooms = `-- name: GetRooms :many
SELECT id, rodada, created_at, result, players, state FROM games
`

func (q *Queries) GetRooms(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, getRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Rodada,
			&i.CreatedAt,
			&i.Result,
			&i.Players,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
